#vim:ft=kitty
font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
remember_window_size no
initial_window_width 800
initial_window_height 540
font_size        13.50
enable_audio_bell no

# BEGIN_KITTY_THEME
# Tokyonight Storm
include tokyonight-storm.conf
# END_KITTY_THEME
