{
  lib,
  stdenvNoCC,
}:

stdenvNoCC.mkDerivation {
  pname = "fcitx5-lightly";
  version = "unstable";

  src = ./lightly;

  phases = [
    "unpackPhase"
    "installPhase"
  ];

  installPhase = ''
    runHook preInstall

    mkdir -p $out/share/fcitx5/themes/lightly
    cp -r * $out/share/fcitx5/themes/lightly

    runHook postInstall
  '';

  meta = with lib; {
    description = "lightly-qt fcitx5 theme (generated by fcitx5 plasma theme)";
    platforms = platforms.all;
  };
}
