[bar.main]
capsule = false
capsule_thickness = 0.75
center = [
  "media",
]
end = [
  "notifications",
  "Spacer-12",
  "tray",
  "Spacer-12",
  "output_volume",
  "input_volume",
]
font_family = "monospace"
margin_edge = 11
margin_ends = 15
padding = 10
position = "top"
radius = 16
scale = 1.15
shadow = false
start = [
  "control-center",
  "Spacer-12",
  "clock",
  "Spacer-12",
  "sysmon_cpu",
  "sysmon_ram",
  "battery",
  "Spacer-12",
  "workspaces",
]
thickness = 38
