# preload = ~/Pictures/wallpaper/arch_fill-transformed.png
# wallpaper = DP-3,contain:~/Pictures/wallpaper/arch_fill-transformed.png
# wallpaper = DP-2,contain:~/Pictures/wallpaper/arch_fill-transformed.png

# preload = ~/Pictures/wallpaper/arch_fill.png
# wallpaper = DP-3,contain:~/Pictures/wallpaper/arch_fill.png
# wallpaper = DP-2,contain:~/Pictures/wallpaper/arch_fill.png

preload = ~/Pictures/wallpaper/simple.png
wallpaper = DP-3,contain:~/Pictures/wallpaper/simple.png
wallpaper = DP-2,contain:~/Pictures/wallpaper/simple.png

